### ISSUE TITLE
DSP usage higher after updating to latest DPF.

### ISSUE THREAD

**Issue by michaelwillis** [DISTRHO/DPF#140]
I updated Dragonfly Reverb to the latest DPF, and testers are reporting that my latest beta release has higher load when showing the GUI. It was using 150c099e1b6e8c184e39be08776e34be1aa0db3f before, and now is using c3bf5ecada36bd49f599f20aba63182522ea04cf. I did a small test of two builds, one for each of those DPF revisions, and found that with the GUI visible, the one built on c3bf5ecada36bd49f599f20aba63182522ea04cf has about 10% higher DSP load. I looked through the changes to DPF since 150c099e1b6e8c184e39be08776e34be1aa0db3f and didn't find anything obvious that would have caused this.

**Comment by falkTX** [comment]
Which version (standalone, lv2, vst) are you testing this with?
The only 2 relevant changes I see are regarding LV2 uiTouch and VST timeInfo.

Would be nice to pin-point where exactly the higher DSP load happens. Does it depend on the plugin format?

Also you say "with GUI visible", does it mean with UI hidden there is less DSP load?
So if I understood right, higher DSP load only happens when UI is visible? and compared to old DPF, there was no such higher DSP load when showing UI?

**Comment by michaelwillis** [comment]
I know that people have experienced it with the VST, but I'm not sure about the LV2, I'll try to test that today.

**Comment by michaelwillis** [comment]
Sorry, it wasn't a problem with DPF at all. I accidentally dropped some compiler optimization flags from my makefiles. It's all better now.
