### ISSUE TITLE
VST3: internal CC params show up in certain hosts

### ISSUE THREAD

**Issue by dromer** [DISTRHO/DPF#345]
We see a giant list of 16 channels 0-129 params in some hosts
Confirmed in Reaper and BespokeSynth (JUCE) generic UIs.

BespokeSynth doesn't list parameters if you have more than 20, not until you then "modify" them. They have a limit of 999 parameters (7*130+89), so we never see the actual plugin params even after "wiggling" their knob.

Works correctly in Carla and Bitwig.

This possibly needs a change on `IMidiMapping, getMidiControllerAssignment or isMidiMapController` as mentioned by @baconpaul

**Comment by falkTX** [comment]
I am closing this as unsupported. 
The VST3 midi mapping stuff is already handled in https://github.com/DISTRHO/DPF/blob/develop/distrho/src/DistrhoPluginVST3.cpp#L3388

In order to support MIDI CC in VST3, we emulate 128 * 16 parameters with that special midi mapping tag, so that changing that param ~= sending a MIDI CC.
It is super hacky, but is what JUCE also ended up doing as it is the only way to receive something close to MIDI CC events.
And what we can see being done on the old surge vst3 side too.

The main different from JUCE to DPF is that JUCE decided to put the CC params at the end, and DPF puts them at the start (a bit easier to manage code-wise)
DPF sets the "hidden" hint for those fake CC params, so proper hosts will not show them.

Our best course of action is just to tell people to not use VST3, it is an awful standard in many ways.

**Comment by dromer** [comment]
So an alternate route would be to request hosts to support this "hidden" hint so they don't show these CC params by default?

**Comment by falkTX** [comment]
yes. or we find some kind of compromise that allows MIDI without those CCs, say a VST3 specific compiler macro.
we lose access to sustain, all-notes-off and some other things typical in MIDI. but depending on the plugin and target that might be ok, not sure...

regarding reaper, seems it is not supported there yet https://forum.cockos.com/showthread.php?t=265985

https://steinbergmedia.github.io/vst3_doc/vstinterfaces/structSteinberg_1_1Vst_1_1ParameterInfo.html for the docs on parameter hints
