### ISSUE TITLE
OSX build of LV2: manifest.ttl has incorrect plugin name

### ISSUE THREAD

**Issue by zamaudio** [DISTRHO/DPF#4]
On OSX builds, the manifest.ttl files needed to be updated as they point to the .dylib as ".dylib.dylib" which do not exist.

**Comment by falkTX** [comment]
I cannot reproduce this.

After updating to latest DPF, the manifest.ttl contents are:
```
<urn:zamaudio:ZaMaximX2>
    a lv2:Plugin ;
    lv2:binary <ZaMaximX2_dsp.dylib> ;
    rdfs:seeAlso <ZaMaximX2_dsp.ttl> .

<urn:zamaudio:ZaMaximX2#UI>
    a ui:CocoaUI ;
    ui:binary <ZaMaximX2_ui.dylib> ;
    rdfs:seeAlso <ZaMaximX2_ui.ttl> .
```

perhaps you need a fresh clone?

**Comment by falkTX** [comment]
the contents of the bundle seems fine too:
```
bin/ZaMaximX2.lv2:
ZaMaximX2_dsp.dylib	ZaMaximX2_ui.dylib	manifest.ttl
ZaMaximX2_dsp.ttl	ZaMaximX2_ui.ttl	presets.ttl
```

**Comment by zamaudio** [comment]
I don't know how I managed to produce this error, because I can't build the final step of .ttl on my GNU/Linux machine using a cross compiler.  Is it possible to make it create the .ttl files regardless of arch?

**Comment by falkTX** [comment]
It needs to be a os-native tool because it opens the shared object.
dlopen() only works if the OS and architecture matches.

What you can do is build a linux version first, copy the ttl somewhere, clean, build the osx version and copy the ttls back.
You'll need to edit some small parts in the ttl, specifically*.so to *.dylib and X11UI to CocoaUI.

**Comment by zamaudio** [comment]
Lets close it, its not really an issue because I can't reproduce it.
