### ISSUE TITLE
Clap: wrong Sample Rate on init

### ISSUE THREAD

**Issue by brummer10** [DISTRHO/DPF#446]
Could it be that the DPF Clap wrapper init plugins with the wrong Sample Rate? I got a report for the StompTuner Clap format only working correct at 44100Hz. That doesn't affect vst2/3 format.
 https://github.com/brummer10/StompTuner/issues/3

**Comment by falkTX** [comment]
yes, not all plugin formats allow to know the correct sample rate when the plugin is created, the `sampleRateChanged` callback is used to indicate that the sample rate is not the same as when first initiated.

this is all normal and expected, not a bug. if that callback is missing that would be a bug, but dont think it is..?

**Comment by falkTX** [comment]
yeah looking at your code the sample rate changes are still TODO, and that would explain the issue.

as per docs in DPF, that callback is only triggered when the plugin is deactivated. so you can safely do reallocations in there.

**Comment by brummer10** [comment]
Okay, Didn't know that. I'll correct that then.

**Comment by falkTX** [comment]
it is the same on VST3 by the way, the proper sample rate is only known when the "audio setup" section.
DPF just has a value as fallback, if it matches the final sample rate then all is good, otherwise it needs a sample rate change. so you cant be sure if it is called or not, best to handle sample rate changes in full.
