### ISSUE TITLE
Implement sendNote on JACK and VST formats

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#50]
For sending notes to the plugin from the UI. 

Relevant method:
https://github.com/DISTRHO/DPF/blob/68b3ca4abe46ee7386cc20574964d1c62c0c1e21/distrho/src/DistrhoUILV2.cpp#L259
https://github.com/DISTRHO/DPF/blob/f8cd00fc49ab0e91a136d109e5478946ae936956/distrho/src/DistrhoUIDSSI.cpp#L183
https://github.com/DISTRHO/DPF/blob/70cec6a9d0222b32abdcaec02cd7b01378c4d78b/distrho/src/DistrhoPluginVST.cpp#L281

Seems like it's implemented for DSSI already. However, I tried it in Renoise and the plugin wouldn't receive the notes.

Jack format doesn't seem to have this method in place.

It seems like I got it working for VST2. Should I send a pull request? (I think you also mentioned using atoms or something like that...)

**Comment by falkTX** [comment]
Sure, send a PR.
Even if I dont merge it directly, the initial code to base on and figure out things is always useful.

I see DSSI is already implemented, which is nice.
I completely forgot I added this method :P

**Comment by pdesaulniers** [comment]
Yes, but as I said, I'm not sure that it works :p

**Comment by pdesaulniers** [comment]
OK, I've got the DSSI UI to open in Carla, and sendNote does work. :)

**Comment by falkTX** [comment]
Now implemented on LV2 format as well.
Not a priority, leaving full implementation for later.

**Comment by olijaun** [comment]
Hi

First of all: thanks a lot for this framework. I'm a complete beginner in audio effects programming and so far it works quite well.

I just managed to get some buttons on the screen and I wanted to send a note when clicking the button. I tried and I tried... Finally I found this issue... The point is I'm testing with the "jack-plugin" because it's quite simple to start...

I can wait for the implementation but you should really at least document this limitation. It would have saved me quite some time.

Thanks and keep up the great work!
Regards
Oliver

**Comment by falkTX** [comment]
> I can wait for the implementation but you should really at least document this limitation.

The limitation is documented in the function itself.
https://github.com/DISTRHO/DPF/blob/master/distrho/DistrhoUI.hpp#L118

There is a PR that implements this for JACK and VST formats.

**Comment by olijaun** [comment]
You're right of course! I'm sorry. Not sure why I haven't seen this. I should only read :-) 
Thanks and Regards
Oliver

**Comment by falkTX** [comment]
This is now handled on the develop branch.
