### ISSUE TITLE
strncpy warnings with GCC 8

### ISSUE THREAD

**Issue by SpotlightKid** [DISTRHO/DPF#63]
WIth GCC 8 I get the following warning on compilation:

```In file included from ../../dpf/distrho/DistrhoPluginMain.cpp:29:
In function 'void DISTRHO::strncpy(char*, const char*, size_t)',
    inlined from 'intptr_t DISTRHO::PluginVst::vst_dispatcher(int32_t, int32_t, intptr_t, void*, float)' at ../../dpf/distrho/src/DistrhoPluginVST.cpp:465:43:
../../dpf/distrho/src/DistrhoPluginVST.cpp:79:17: warning: 'char* strncpy(char*, const char*, size_t)' output may be truncated copying 23 bytes from a string of length 32 [-Wstringop-truncation]
     std::strncpy(dst, src, size-1);
     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

Since the custom `DISTRHO::strncpy` function inserts a null char at `size-1` in any case, can't we just use `std::memcpy` instead of `std::strncpy` to get rid of the warning?

**Comment by falkTX** [comment]
no, because strncpy copies only till the end of the string.
if we use memcpy we need to have the last parameter as `std::min(std::strlen(src), size-1)`
I don't get the warning myself, so a PR is welcome

**Comment by SpotlightKid** [comment]
> I don't get the warning myself, so a PR is welcome

You mean like this: #64?

**Comment by falkTX** [comment]
yes, though now we have to make sure the size > 0, otherwise the -1 would underflow.
put a `DISTRHO_SAFE_ASSERT_RETURN(size > 0,)` just before the memcpy.
we are the ones calling those functions, so it should be safe, but if sometime in the future we use it for more random things, it will catch the mistake.

Also, there are 2 similar functions which could have the same treatment ;)
