### ISSUE TITLE
Latest version of DPF repeatedly resizes on MacOS REAPER.

### ISSUE THREAD

**Issue by michaelwillis** [DISTRHO/DPF#90]
This bug was reported on my plugin:

https://www.youtube.com/watch?v=cJen6BnAPcE

I tried to reproduce using Distrho Mini-Series 3 Band EQ. I checked out Mini-Series, built it for MacOS, loaded it in REAPER, and did not observe the bug. Then I noticed that Mini-Series is using an older DPF. I updated the `dpf` submodule to the latest, rebuilt Mini-Series, and then the 3 Band EQ did reproduce the bug; this seems to indicate that the bug has been introduced in a recent version of DPF.

**Comment by michaelwillis** [comment]
I used git bisect on the `dpf` submodule.

Last good revision before this bug started happening:

```
commit 981e61a807280ea91bece2780e75ee3a48949675
Author: falkTX <falktx@gmail.com>
Date:   Sun Sep 30 14:38:26 2018 +0200

    Small adjustments to Window
```

The next revision crashes REAPER on MacOS:
```
commit a1748a1a9fd1ac6f8b8abaa26cec64f121d13d7e
Author: falkTX <falktx@gmail.com>
Date:   Sun Sep 30 16:03:28 2018 +0200

    Assume Windows to be resizable by default; Add UI::isUserResizable
```

The following revision exhibits the bug:
```
commit b526e381cc065e44dc8ec7620c1725b203a3ee85 (HEAD, refs/bisect/bad)
Author: falkTX <falktx@gmail.com>
Date:   Sun Sep 30 16:48:43 2018 +0200

    Fix recursive resizing in certain DAWs
```

**Comment by michaelwillis** [comment]
The weird thing is that I haven't seen this bug happen on any other DAW, and it doesn't happen on the Linux or Windows flavors of REAPER.

**Comment by zamaudio** [comment]
I think this is caused by fResizable being initialized to true in the window constructor.  I believe this is in preparation for having resizable uis with fixed aspect ratio and falktx turned on the resizable flag, but I don't think this feature is ready yet... (?)

**Comment by falkTX** [comment]
I ended up not finishing, correct.
Actually, now looking closer it is better I revert a1748a1a9fd1ac6f8b8abaa26cec64f121d13d7e.
I should push these changes to a branch and not master, then only merge when complete.

**Comment by falkTX** [comment]
@michaelwillis Please update DPF and retest, I guess it will work fine again for now.

Since we are here discussing resizable UIs, I am thinking of making that a build-time, per-plugin macro.
Something that will be added in DistrhoPluginInfo.h.
We make UIs non-resizable by default, and allow to have this macro for devs that want a specific plugin UI to be resizable (NOTE: this is resizing by the user, you can always do it manually in the plugin)
Just a simple `#define DISTRHO_UI_USER_RESIZABLE 1` to enable it.
This will make everything much simpler.

@pdesaulniers since you already use resizing, what do you think of the above?

**Comment by pdesaulniers** [comment]
@falkTX Seems like a clean way of dealing with this. 

I haven't really used user resizing, though, since it wouldn't work so well with my `setSize` resize handle approach. IIRC, the window would end up oscillating between two sizes after a resize with the handle. I want to keep that handle, because I use it to make the VST2 UI resizable.

I'd like to give this feature another go. A plugin that would benefit from this feature would be https://github.com/pdesaulniers/wolf-spectrum . It uses my fork of DPF for now, but it should be easy to switch it back to upstream DPF.

**Comment by michaelwillis** [comment]
@falkTX Confirmed, the latest DPF does not exhibit this bug. Thanks!

**Comment by falkTX** [comment]
FYI `DISTRHO_UI_USER_RESIZABLE` macro has now been pushed to master.
The meters and info example plugins have it enabled, you can see their UIs scale with the host if you load the LV2 versions :D

**Comment by michaelwillis** [comment]
@falkTX Nice, thanks for the heads up!
