### ISSUE TITLE
Simplify Windows build

### ISSUE THREAD

**Issue by codecat** [DISTRHO/DPF#91]
I was not able to build DPF on Windows due to the fact that there's only makefiles. I had to work around several MinGW issues:

* Making a symbolic link to gcc so that "cc" can be recognized (not sure why this was necessary)
* My MinGW has a `glext.h` from 2002, which obviously breaks the build since that's way too old
* ...and I didn't really go any further because I don't know how to fix that issue.

Perhaps there should be a Visual Studio project/solution? Or better documentation on how to set up MinGW and build it on Windows?

(I must be doing something wrong setting up and building with MinGW, I hope someone can point me in the right direction.)

**Comment by codecat** [comment]
Related: #54

**Comment by falkTX** [comment]
I do not use windows, no idea how people manage projects there.
I rather not have VS projects, since I will never use myself and it will need dedicated overview whenever I decide to change small things...

For you issues, the "cc" being needed I guess is just because you do not have `CC` environment variable set.
something like this should work:
```
setx CC mingw-gcc.exe
setx CXX mingw-g++.exe
make
```

I am willing to add more compat stuff regarding GL extensions.
There are already a few in place for the most common stuff, mostly OpenGL2 things.
If you post a full build log, I can add the missing bits and we keep trying till it builds.

**Comment by codecat** [comment]
Honestly, keeping compatibility with an OpenGL library from 2002 seems like madness. I don't think time should be spent on that, to be perfectly honest. If anything, I should figure out how to get a mingw version without an updated set of GL libraries.

Have you considered using a build system like CMake to generate projects instead? This is cross-platform so it should simplify builds on all platforms.

**Comment by falkTX** [comment]
I do not see how cmake would help here at all.
Makefiles are cross-platform already.
Windows 10 with Linux subsystem thing can now have it calling windows executables, so we have an environment to build stuff for Windows.

I do not know cmake or waf enough to make such thing myself.

**Comment by falkTX** [comment]
I am going over tickets in DPF, and will close this one.
the existing makefiles already detect the target architecture based on the compiler used. this is more than enough for me and for most use-cases.
adding support for waf, cmake or any other is something separate
